FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dbt_demo/greenwheel/ .
COPY docker/dbt/profiles.yml /root/.dbt/profiles.yml

ENTRYPOINT ["dbt"]
CMD ["debug"]
